
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama  # Bind mount for persistent storage
    restart: unless-stopped
    command: serve
